---

- name: Translate engagement data into Argo-processable resources
  hosts: local
  gather_facts: false
  tasks:
    - name: Read Engagement Data
      include_vars:
        file: "{{ directory }}/engagement.json"
    - name: Verify governor_type is specified
      fail:
        msg: "Please verify that a governor_type and governor_spec has been specified in your inventory"
      when:
        - (governor_type is undefined or (governor_type | trim) == "") or (governor_spec is undefined or (governor_spec | trim) == "")
    - block:
      - include_tasks: tasks/envs.yaml
        with_items: "{{ hosting_environments }}"
        loop_control:
          loop_var: hosting_env
      when:
        - hosting_environments is defined
        - hosting_environments|length > 0
      
