---

- name: Generate identity-management inventory based off of engagement.json
  hosts: local
  gather_facts: false
  tasks:

  - name: "Fail If Working Directory Is Not Provided"
    fail:
      msg: "directory var needs to be provided in order to ensure a safe working directory"
    when:
      - directory is undefined or (directory | trim) == ""

  - name: Read Engagement Data
    include_vars:
      file: "{{ directory }}/engagement.json"

  - name: Read Credentials
    include_vars:
      file: "{{ directory }}/{{ config_dir }}/{{ item }}"
    loop:
      - "ocp-admin-credentials.json"

  - name: "Add users to inventory"
    set_fact:
      users: "{{ (users | default([])) +  [ { 'first_name': (item.first_name | trim), 'last_name': (item.last_name | trim), 'email': (item.email | trim) , 'user_name': (item.first_name | trim | lower)[0] + (item.last_name | trim | lower) } ] }}"
    loop: "{{ engagement_users }}"

  - name: "Get Unique Groups"
    set_fact:
      unique_groups: "{{ engagement_users | json_query('[].role') | unique }}"

  - name: "Set Group Membership"
    set_fact:
      usrgrp: "{{ (usrgrp | default([])) + [ {'name': item, 'members': (engagement_users |  json_query(query)) } ] }}"
    vars:
      query: "[?role =='{{ item }}'].email"
    loop: "{{ unique_groups }}" 

  - name: Add Group of Groups
    set_fact:
      usrgrp: "{{ (usrgrp | default([])) + [ {'name': 'ldap-users', 'childgroups': unique_groups } ] }}"

  - name: "Set IDM facts"
    set_fact:
      ipa_host: "{{ 'https://ipa.apps.' + (ocp_sub_domain | lower) + '.' + (engagement_region | default('na') | lower) +'-1.' + ocp_base_url }}" 
      ipa_admin_user: "{{ ocp_admin_username }}"
      ipa_admin_password: "{{ ocp_admin_password }}"
      ipa_validate_certs: "{{ ipa_validate_certs | default(true) }}"

  - name: "Assemble inventory"
    set_fact:
      claim_content: "{{ { 'ipa_validate_certs': ipa_validate_certs, 'ipa_host': ipa_host, 'ipa_admin_user': ipa_admin_user, 'ipa_admin_password': ipa_admin_password, 'identities': { 'users': users, 'groups': usrgrp } } | to_nice_yaml(indent=2) }}"

  - name: "Write inventory to file"
    copy:
      content: "{{ claim_content }}"
      dest: "{{ directory }}/iac/inventories/identity-management/inventory/group_vars/all.yml"

  - name: "Create hosts file"
    copy:
      content: "[identity-hosts]\nlocalhost"
      dest: "{{ directory }}/iac/inventories/identity-management/inventory/hosts"

  - name: "Assemble governor name"
    set_fact:
      governor_name: "{{ 'labs.ocp4.' + (engagement_region | default('na') | lower) }}"


  - name: "Create ResourceClaim"
    copy:
      content: "{{ lookup('template', inventory_dir + '/../files/templates/resourceclaim.yaml.j2') }}"
      dest: "{{ directory }}/ocp-init/id-mgmt.yaml"
