---

- name: Set fact used to check if a hosting environment is needed
  set_fact:
    ocp_cloud_provider_name: "{{ hosting_env.ocp_cloud_provider_name | default('other') }}"

- block:
    - name: Read credentials
      include_vars:
        file: "{{ directory }}/{{ config_dir }}/{{ item }}"
      loop:
        - "ocp-admin-credentials.json"
        - "ocp-ldap-sa-credentials.json"
    - name: Create OCP manifest directory if not present
      file:
        path: "{{ directory }}/ocp-init"
        state: directory
    - name: Create Resource Claim
      vars:
        claim_content:
          email: "{{ engagement_lead_email }}"
          admin_user: "{{ ocp_admin_username }}"
          admin_password: "{{ ocp_admin_password }}"
          aws_region: "{{ hosting_env.ocp_cloud_provider_region }}"
          customer_name: "{{ customer_name }}"
          customer_project: "{{ project_name }}"
          engagement_uuid: "{{ uuid }}"
          ocp4_installer_version: "{{ hosting_env.ocp_version }}"
          ocp_ldap_sa_user: "{{ ocp_ldap_sa_username }}"
          ocp_ldap_sa_password: "{{ ocp_ldap_sa_password }}"
          ocp_subdomain: "{{ hosting_env.ocp_sub_domain }}"
      copy:
        content: "{{ lookup('template', inventory_dir + '/../files/templates/resourceclaim.yaml.j2') }}"
        dest: "{{ directory }}/ocp-init/cluster-init-{{ (hosting_env.environment_name |  trim) | regex_replace(' ','-') | lower }}.yaml"
  when:
    - ocp_cloud_provider_name|trim != 'other'
