---

- name: Setup output dir
  import_playbook: output_dir.yml

- name: Completion Callback
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Skip completion callback
      meta: end_play
      when:
        - agnosticd_callback_disabled is defined
        - agnosticd_callback_disabled | bool

    - name: Attempt completion callback
      when:
        - agnosticd_callback_url != ''
        - agnosticd_callback_token != ''
      vars:
        user_body_yaml: "{{ output_dir ~ '/user-body.yaml' }}"
        user_data_yaml: "{{ output_dir ~ '/user-data.yaml' }}"
        user_info_yaml: "{{ output_dir ~ '/user-info.yaml' }}"
      uri:
        url: "{{ agnosticd_callback_url }}"
        method: POST
        body_format: json
        body:
          event: complete
          message_body: >-
            {%- if user_body_yaml is file -%}
            {{ lookup('file', user_body_yaml) | from_yaml | default([], true) }}
            {%- else -%}
            []
            {%- endif -%}
          messages: >-
            {%- if user_info_yaml is file -%}
            {{ lookup('file', user_info_yaml) | from_yaml | default([], true) }}
            {%- else -%}
            []
            {%- endif -%}
          data: >-
            {%- if user_data_yaml is file -%}
            {{ lookup('file', user_data_yaml) | from_yaml | default({}, true) }}
            {%- else -%}
            {}
            {%- endif -%}
        headers:
          Authorization: Bearer {{ agnosticd_callback_token }}
        validate_certs: "{{ validate_tower_certs | default(true) }}"
      # Best effort
      ignore_errors: true
