---

- hosts: identity-hosts
  name: Verify Identity Provider
  tasks:
    - name: "Fail if ocp_subdomain or subdomain_base_suffix not provided"
      fail:
        msg: "ocp_subdomain and subdomain_base_suffix vars needs to be provided in order to continue withe the playbook"
      when:
        - ocp_subdomain is undefined or subdomain_base_suffix is undefined

    - set_fact:
        ipa_host: "ipa.apps.{{ ocp_subdomain }}.{{ subdomain_base_suffix }}"

    - name: Wait for IdM to be responsive
      uri:
        url: "https://{{ ipa_host }}/ipa/ui/"
        validate_certs: "{{ ipa_validate_certs }}"
      register: rc
      until: rc.status|trim|int == 200
      retries: 90
      delay: 60

- name: Remove participants from IdM
  import_playbook: "process_remove.yml"
  when:
    - lodestar_identities_remove.users is defined
    - lodestar_identities_remove.users != []

- name: Add participants to IdM
  import_playbook: "process_add.yml"
  when:
    - lodestar_identities.users is defined
    - lodestar_identities.users != []

- name: Update Anarchy with status
  import_playbook: completion_callback.yml
