---

- hosts: identity-hosts
  name: Verify Identity Provider
  tasks:

    - name: Wait for IdM to be responsive
      uri:
        url: "https://{{ ipa_host }}/ipa/ui/"
        validate_certs: "{{ ipa_validate_certs }}"
      register: rc
      until: rc.status|trim|int == 200
      retries: 90
      delay: 60
      when:
        - ipa_host is defined

- name: Remove participants from IdM
  import_playbook: "process_remove.yml"
  when:
    - lodestar_identities_remove.users is defined
    - lodestar_identities_remove.users != []

- name: Add participants to IdM
  import_playbook: "process_add.yml"
  when:
    - lodestar_identities.users is defined
    - lodestar_identities.users != []

- name: Update Anarchy with status
  import_playbook: completion_callback.yml
