---
# vim: set ft=ansible:

################################################################################
# Entry point used to send a completion callback and ends the playbook without action
################################################################################

- import_playbook: completion_callback.yml

- name: End Playbook
  gather_facts: false
  hosts: localhost
  tasks:
    - meta: end_play
