---
- name: Generate email notifications to be consumed by Ansible Tower scheduled jobs
  hosts: notification_host
  gather_facts: false
  
  tasks:
    - name: "Fail if directory and email_templates_directory are not provided"
      fail:
        msg: "directory and email_templates_directory vars needs to be provided in order continue with the playbook"
      when:
        - directory is undefined or (directory | trim) == ""
        - email_templates_directory is undefined or (email_templates_directory | trim) == ""

    - name: "Read Engagement Data"
      include_vars:
        file: "{{ directory }}/engagement.json"

    - name: "Check for existing email templates"
      stat:
        path: "{{ directory }}/iac/inventories/notifications/inventory/group_vars/all"
      register: notifications_dir

    - name: "Copy email templates from main repo to engagement repo - if the target directory does NOT already exist"
      block:
        - name: "Add directory for group_vars/all"
          file:
            path: "{{ directory }}/iac/inventories/notifications/inventory/group_vars/all"
            state: directory

        - name: "Copy email template directory to Residency Engagement repo and process as jinja2"
          template:
            src: "{{ item }}"
            dest: "{{ directory }}/iac/inventories/notifications/inventory/group_vars/all/{{ item | basename | regex_replace('.j2$') }}"
          with_fileglob:
            - "{{ email_templates_directory }}/hosting/residency/{{ language | default('en_us') }}/*.j2"
          when: engagement_type | default('') == 'Residency'

        - name: "Copy email template directory to DO500 Engagement repo and process as jinja2"
          template:
            src: "{{ item }}"
            dest: "{{ directory }}/iac/inventories/notifications/inventory/group_vars/all/{{ item | basename | regex_replace('.j2$') }}"
          with_fileglob:
            - "{{ email_templates_directory }}/hosting/do500/{{ language | default('en_us') }}/*.j2"
          when: engagement_type | default('') == 'DO500'

        - name: "Create hosts file"
          copy:
            src: "hosts"
            dest: "{{ directory }}/iac/inventories/notifications/inventory/hosts"

      when: 
        - notifications_dir.stat.exists is false
        - start_date is defined
        - engagement_type | default('') == 'Residency' or engagement_type | default('') == 'DO500'
        - (hosting_environments is defined) and (hosting_environments | length > 0)
        - (archive_date | default('2006-01-02T15:04:05.000Z') | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ')).strftime('%s') > now(utc=true).strftime('%s')

    - name: "Process list of users from template"
      template:
        src: list-of-users.yaml.j2
        dest: "{{ directory }}/iac/inventories/notifications/inventory/group_vars/all/list_of_users.yaml"
      when: 
        - start_date is defined
        - engagement_type | default('') == 'Residency' or engagement_type | default('') == 'DO500'
        - (hosting_environments is defined) and (hosting_environments | length > 0)
        - (archive_date | default('2006-01-02T15:04:05.000Z') | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ')).strftime('%s') > now(utc=true).strftime('%s')
